#-----------------------------------------------------------------------------
# FILE NAME:	Makefile
#
# DESCRIPTION:  Makefile for a C++ program
#
# PURPOSE:	Build a program executable on Linux
#
# MODIFICATION HISTORY:
#
# Author	       Date	    Modifications(s)
# -----------	       ---------    ----------------
# Michael Des Roches   2018-02-01   Version 1
#_____________________________________________________________________________

#	This is our original generic makefile command that will build
#	any stand alone ".cpp" source file.
#	Usage: e.g, make hello

.cpp :
	g++ -o $* $*.cpp -std=c++11

bankacct_v2 : bankacct_v2.h
bankacct_v3 : bankacct_v3.h
bankacct_v4 : bankacct_v4.h
